services:
  backend:
    build: ./ocha-auth-pro--fastify@node
    container_name: ocha_backend
    ports:
      - "127.0.0.1:3002:3002"
    env_file:
      - ./ocha-auth-pro--fastify@node/.env
    depends_on:
      - postgres
      - redis
    dns:
      - 127.0.0.11
      - 8.8.8.8
    networks:
      - ocha-net

  frontend:
    build: ./ocha-auth-pro--qwik@node
    container_name: ocha_frontend
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ORIGIN=https://ocha-auth-pro.ochacoder.com
    env_file:
      - ./ocha-auth-pro--qwik@node/.env.local
    depends_on:
      - backend
    dns:
      - 127.0.0.11
      - 8.8.8.8
    networks:
      - ocha-net

  postgres:
    image: postgres:16
    container_name: ocha_postgres
    environment:
      POSTGRES_DB: ochadb
      POSTGRES_USER: ocha
      POSTGRES_PASSWORD: o7RPv_Yh_GcWlv7a-dXAz8pj6NBdiujVIK-z_4CSCYsnSi02uFl8LMY-mVJ7-2yyb6SXdpBpRhtY4kzn39Okyg
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./ocha-auth-pro--fastify@node/db/migrations/init_users.sql:/docker-entrypoint-initdb.d/init_users.sql
    dns:
      - 127.0.0.11
      - 8.8.8.8
    networks:
      - ocha-net

  redis:
    image: redis:7
    container_name: ocha_redis
    command: redis-server --requirepass Drp9XfyrsMZ9jZFnVYGVJrh-MqZhbKQtYSJMzz7gGgjOgrbIOX606f2yXmPSWhHyyqdPSZm9LOhiUJ4ejjANQA
    volumes:
      - redis-data:/data
    dns:
      - 127.0.0.11
      - 8.8.8.8
    networks:
      - ocha-net

  monitor:
    build:
      context: ./ocha-auth-pro--fastify@node
      dockerfile: Dockerfile.monitor
    container_name: ocha_monitor
    ports:
      - "127.0.0.1:9090:9090"
    env_file:
      - ./ocha-auth-pro--fastify@node/.env
    depends_on:
      - postgres
      - redis
    dns:
      - 127.0.0.11
      - 8.8.8.8
    networks:
      - ocha-net

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://ocha:o7RPv_Yh_GcWlv7a-dXAz8pj6NBdiujVIK-z_4CSCYsnSi02uFl8LMY-mVJ7-2yyb6SXdpBpRhtY4kzn39Okyg@ocha_postgres:5432/ochadb?sslmode=disable
    depends_on:
      - postgres
    dns:
      - 127.0.0.11
      - 8.8.8.8
    networks:
      - ocha-net

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter
    environment:
      - REDIS_ADDR=redis://ocha_redis:6379
      - REDIS_PASSWORD=Drp9XfyrsMZ9jZFnVYGVJrh-MqZhbKQtYSJMzz7gGgjOgrbIOX606f2yXmPSWhHyyqdPSZm9LOhiUJ4ejjANQA
    depends_on:
      - redis
    dns:
      - 127.0.0.11
      - 8.8.8.8
    networks:
      - ocha-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "127.0.0.1:19090:9090"
    volumes:
      - ./ocha-auth-pro--fastify@node/src/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    dns:
      - 127.0.0.11
      - 8.8.8.8
    networks:
      - ocha-net

  grafana:
    image: grafana/grafana:latest
    container_name: ocha_grafana
    ports:
      - "127.0.0.1:3001:3000" # Internal port is 3000, exposed as 3001
    environment:
      - GF_SECURITY_ADMIN_USER=ochacoder
      - GF_SECURITY_ADMIN_PASSWORD=ocha1234
      - GF_SERVER_ROOT_URL=https://grafana.ochacoder.com/
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - ocha-net

volumes:
  pg-data:
  redis-data:
  prometheus-data:
  grafana-data:

networks:
  ocha-net:
