{
 "title": "Ocha-Auth-Pro",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center; gap: 12px; font-family: sans-serif;\">\n  <img src=\"https://grafana.com/static/img/menu/grafana2.svg\" alt=\"Grafana Logo\" style=\"height: 32px;\" />\n  <h1 style=\"margin: 0; font-size: 24px;\">OchaAuthPro Monitoring Dashboard</h1>\n</div>\n"
   }
  },
  {
   "title": "Postgres Health Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres_available{app=\"ocha-auth\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Health Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_available{app=\"ocha-auth\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monitor Server Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_uptime_seconds{app=\"ocha-auth\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monitor Server Uptime",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uptime_seconds{app=\"ocha-auth\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}